config/routes.rb
Rails.application.routes.draw do

  root to: 'maze#index'

  post 'maze/seek'
  post 'maze/redraw'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maze_controller.rb
class MazeController < ApplicationController
  include MinCost

  def index
    height0, width0 = 10,10

    @height = (params[:height] || height0).to_i
    @width = (params[:width] || width0).to_i
    @start = start_pos
    @goal = goal_pos

    @maze = to_maze_hash(base_maze)
  end

  def redraw
    redirect_to action: :index and return unless get_state_from_json
    redirect_to action: :index and return unless (params[:height] && params[:width])

    @height = params[:height].to_i
    @width = params[:width].to_i
    @start = start_pos
    @goal = goal_pos

    maze_body = render_to_string partial: 'maze/maze', locals: {height: @height, width: @width, maze: @maze, start: @start, goal: @goal}
    render json: {maze: maze_body}
  end

  def seek
    redirect_to action: :index and return unless get_state_from_json
    redirect_to action: :index and return unless params[:algorithm]
    cost_algorithm = params[:algorithm].to_sym

    # @path = path_with_min_cost(@start, @goal, @maze, algorithm: :minimum_distance)
    @path = path_with_min_cost(@start, @goal, @maze, algorithm: cost_algorithm)

    respond_to do |format|
      format.json do
        render json: {path: @path, start: @start, goal: @goal, maze: @maze, algo: cost_algorithm}
      end
    end
  end


  private

    def base_maze
      %w(
      .##.......
      ..#.###.#.
      .##...#.#.
      ..#..##.#.
      #.#..#..#.
      #.#..#....
      #.#..#.##.
      ..#..#..#.
      .#...##.#.
      ...#....#.
      )
    end
    def start_pos
      @start = [0,0]
    end
    def goal_pos
      @goal = [@height-1, @width-1]
    end

    def get_state_from_json
      return nil unless (params[:height] && params[:width] && params[:cell_status])

      @height = params[:height].to_i
      @width = params[:width].to_i
      cell_class = params[:cell_status].values

      @maze = {}
      cell_class.each do |c_id, c_cls|
        _, y, x = c_id.split('-').map(&:to_i)
        if c_cls.include? 'cell-wall'
          @maze[[y,x]] = nil
        else
          @maze[[y,x]] = 1
          if c_cls.include? 'cell-start'
            @start = [y,x]
          elsif c_cls.include? 'cell-goal'
            @goal = [y,x]
          end
        end

      end

      @maze
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maze_helper.rb
module MazeHelper

  def cell_type(h, w, maze, start, goal)
    return 'cell-start'  if [h, w] == start
    return 'cell-goal' if [h, w] == goal

    case maze[[h, w]]
    when nil
      'cell-wall'
    when 1
      'cell-space'
    end
  end

  def cell_icon(h, w, maze, start, goal)
    return 'glyphicon glyphicon-log-in cell-icon-start'  if [h, w] == start
    return 'glyphicon glyphicon-log-out cell-icon-goal' if [h, w] == goal

    case maze[[h, w]]
    when nil
      'cell-icon-wall'
    when 1
      'cell-icon-space'
    end
  end

end

app/views/home/index.html.erb
<div class='container'>
  <div class='col-md-offset-2 col-md-8'>

    <div class='title col-md-8'>
      <h1>MaZeeeeen</h1>
    </div>
    <div class='col-md-8 panel panel-default'>
      <table id='target-maze'>
        <% @height.times do |h| %>
          <tr class="row row-<%= "#{h}" %>">
          <% @width.times do |w| %>
            <td class="cell col-<%= "#{w}" %> <%= cell_type(h, w) %>" id="cell-<%= "#{h}-#{w}" %>">
              <span class='<%= cell_icon(h, w) %>'>
            </td>
          <% end %>
          </tr>
        <% end %>
      </table>
    </div>

    <div class='col-md-4 control-box'>
      <div class='col-md-12 execute-btn-box'>
        <div class='form-group'>
          <%= button_to "経路を算出", root_path, class: 'btn btn-success form-control' %>
        </div>
      </div>
      <div class='col-md-12 config-box'>
        <form class='form-inline'>
          <div class='form-group'>
            <%= form_tag root_path, method: :get do %>
              <div class='input-group'>
                <div class='input-group-addon'> <%= "高さ" %> </div>
                <%= number_field_tag :height, @height, class: 'form-control' %>
              </div>
              <div class='input-group'>
                <div class='input-group-addon'> <%= "幅　" %> </div>
                <%= number_field_tag :width, @width, class: 'form-control' %>
              </div>
              <div class='size-change-btn'>
                <%= submit_tag '変更', class: 'btn btn-block btn-info' %>
              </div>
            <% end %>
          </div>
        </form>
      </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mazeen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maze/_maze.html.erb
<table id='target-maze'>
  <% height.times do |h| %>
    <tr class="row row-<%= "#{h}" %>">
    <% width.times do |w| %>
      <td class="cell col-<%= "#{w}" %> <%= cell_type(h, w, maze, start, goal) %>" id="cell-<%= "#{h}-#{w}" %>">
        <span class='<%= cell_icon(h, w, maze, start, goal) %>'>
      </td>
    <% end %>
    </tr>
  <% end %>
</table>

app/views/maze/index.html.erb
<div class='container'>
  <div class='col-md-offset-1 col-md-10'>

    <div class='title col-md-9'>
      <h1>mazeeeeen</h1>
    </div>
    <div class='col-md-8 panel panel-default' id='maze-body'>
      <%= render partial: 'maze/maze', locals: {height: @height, width: @width, maze: @maze, start: @start, goal: @goal} %>
    </div>

    <div class='col-md-3 control-box'>
      <div class='col-md-12 seek-btn-box'>
        <div class='form-group'>
          <%= button_to "探索", maze_seek_path, class: 'btn btn-success form-control seek-btn', remote: true %>
        </div>
        <div class='form-group'>
          <div class="radio" id='cost-algorithm-select'>
            <label>
              <input type="radio" name="cost-algorithm" id="cost-algorithm-1" value="min_distance" checked>
              移動距離を最小にする
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="cost-algorithm" id="cost-algorithm-2" value="min_turns">
              方向転換の回数を最小にする
            </label>
          </div>
        </div>
      </div>
      <div class='col-md-12 config-box'>
        <form class='form-inline'>
          <div class='form-group'>
            <%= form_tag root_path, method: :get do %>
              <div class='input-group'>
                <div class='input-group-addon'> <%= "高さ" %> </div>
                <%= number_field_tag :height, @height, class: 'form-control', id: 'maze-height' %>
              </div>
              <div class='input-group'>
                <div class='input-group-addon'> <%= "幅　" %> </div>
                <%= number_field_tag :width, @width, class: 'form-control', id: 'maze-width' %>
              </div>
              <div class='size-change-btn'>
                <%= submit_tag '変更', class: 'btn btn-block btn-info size-change-btn', remote: true %>
              </div>
            <% end %>
          </div>
        </form>
      </div>
  </div>
  </div>
</div>

app/views/maze/seek.js.erb
$('#maze-body').html('<%= j(render(partial: 'maze/maze', locals: {height: @height, width: @width, maze: @maze, start: @start, goal: @goal} )) %>');